sudo: required
services:
    - docker

before_install:
  - docker build -t felipeparreirafb/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run felipeparreirafb/react-test npm test -- --coverage

after_success:
  - docker build -t felipeparreirafb/multi-client ./client
  - docker build -t felipeparreirafb/multi-nginx ./nginx
  - docker build -t felipeparreirafb/multi-server ./server
  - docker build -t felipeparreirafb/multi-worker ./worker
  # Log in to the DOcker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push them to Docker hub
  - docker push felipeparreirafb/multi-server
  - docker push felipeparreirafb/multi-client 
  - docker push felipeparreirafb/multi-nginx
  - docker push felipeparreirafb/multi-worker

deploy: 
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-1-413368079059
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY